server:
  port: 8001
spring:
  application:
    name: cloud-payment-servcie
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://123.207.252.249:3306/db2020?userUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: mch1021
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/pages/
      suffix: .html
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问可以显示IP

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.entity

